Initial PR
shogun-toolbox/applications pull request #1
Opened 2020-05-15 15:33 UTC by Hephaestus12

Writing basic web app.

2020-05-15 21:17 UTC, karlnapf commented on influenza_project/.gitignore
> +cython_debug/
See also https://github.com/shogun-toolbox/shogun/blob/develop/.gitignore

2020-05-15 21:17 UTC, karlnapf commented on influenza_project/README.md
> +## GSOC 2020 Influenza Project
could you slight change the folder structure, and create a folder `gsoc_application_projects/2020/influenza` ?

2020-05-15 21:18 UTC, karlnapf commented on influenza_project/web/keywords/keywords_belgium.txt
> +Aviair_reovirus
where do these come from?

2020-05-15 21:19 UTC, karlnapf commented on influenza_project/web/keywords/keywords_netherlands.txt
> +Zaïre_ebolavirus
Id suggest to not have these....all this stuff is kind of unrelated

2020-05-15 21:19 UTC, karlnapf commented on influenza_project/web/requirements.txt
> +Flask==1.1.2
do you need all of those or is this copy pasted?

2020-05-15 21:20 UTC, karlnapf commented on influenza_project/web/keywords/keywords_netherlands.txt
> +Zaïre_ebolavirus
ah sorry I realise now that these are the wiki search queries?

2020-05-15 21:21 UTC, karlnapf commented on influenza_project/web/app.py
> +            res = pageviewapi.per_article(project, line.strip(), start, end, access='all-access', agent='all-agents', granularity='daily')
maybe respect the 80 char limit

2020-05-15 21:22 UTC, karlnapf commented on influenza_project/web/app.py
> +        #use model to predict values using the features vector and store in cases
I suggest for PRs ... just dont commit code that you dont need instead of submitting commented out code

2020-05-15 21:23 UTC, karlnapf reviewed
Good to see a first PR :)

2020-05-16 01:59 UTC, Hephaestus12 commented on influenza_project/README.md
> +## GSOC 2020 Influenza Project
Yes, sure.

2020-05-16 01:59 UTC, Hephaestus12 commented on influenza_project/.gitignore
> +cython_debug/
I'll add these too?

2020-05-16 02:01 UTC, Hephaestus12 commented on influenza_project/web/keywords/keywords_netherlands.txt
> +Zaïre_ebolavirus
Yes, these are the keywords(names of articles) who's pageviews we will be using as features in the regression.

2020-05-16 02:03 UTC, Hephaestus12 commented on influenza_project/web/requirements.txt
> +Flask==1.1.2
No, this wasn't copy-pasted. After installing all the dependencies as and when I needed them while writing the code, I did a simple
```
pip freeze > requirements.txt
```
to generate this file.
Do some of them appear to not be useful?

2020-05-16 02:04 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +            res = pageviewapi.per_article(project, line.strip(), start, end, access='all-access', agent='all-agents', granularity='daily')
Yes, okay. I'll wrap the line.

2020-05-16 02:05 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +        #use model to predict values using the features vector and store in cases
Okay, I'll have this removed.

2020-05-16 02:08 UTC, Hephaestus12 commented
Also, what python version should I use?
Is there any requirement with respect to that?
I have used 3.7 here, but as far as I know, Shogun can only be used on version 3.5

So, I should switch to that right? Or is this okay?

2020-05-16 04:54 UTC, Hephaestus12 commented
Also, for the web app, should I set up a database and use something like SQLAlchemy(a python wrapper for SQL) or simply use pandas?

2020-05-16 06:26 UTC, gf712 commented on influenza_project/web/app.py
> +            res = pageviewapi.per_article(project, line.strip(), start, end, access='all-access', agent='all-agents', granularity='daily')
I guess you can just do a round of pep8 if that is what we are aiming for as a standard?

2020-05-16 06:34 UTC, gf712 commented on influenza_project/web/app.py
> +    with filepath.open() as file:
Btw, it might have changed, but isn’t the pythonic thing to do with open(filename, “r”) as file?

2020-05-16 06:34 UTC, gf712 commented on influenza_project/web/app.py
> +    prefix = {'austria':'de', 'belgium':'nl', 'germany':'de', 'italy':'it', 'netherlands':'nl'}
Austria  is probably not de, i think it’s at?That’s Germany no? Or is it the same? Same with Belgium (be)

2020-05-16 06:34 UTC, gf712 commented on influenza_project/web/requirements.txt
> +Flask==1.1.2
They all seem pretty standard to me. I guess they can be a bit restrictive. Some of these are probably just Flask direct dependencies and you can probably get away with a lower version? Then again you would deploy this in a docker env, so it doesn’t matter if the versions are super restrictive

2020-05-16 08:39 UTC, geektoni commented on influenza_project/web/app.py
> +    prefix = {'austria':'de', 'belgium':'nl', 'germany':'de', 'italy':'it', 'netherlands':'nl'}
@gf712 these variables are used to access Wikipedia's websites (e.g. `de.wikipedia.org`). The prefix refers to the language spoken.

2020-05-16 08:42 UTC, geektoni commented
> Also, what python version should I use?
> Is there any requirement with respect to that?
> I have used 3.7 here, but as far as I know, Shogun can only be used on version 3.5
> 
> So, I should switch to that right? Or is this okay?

I think I've answered these questions in the email I sent you :) python 3.5 would be okay for now.

2020-05-16 08:43 UTC, geektoni commented
> Also, for the web app, should I set up a database and use something like SQLAlchemy(a python wrapper for SQL) or simply use pandas and csv files?

mmh what do you plan to use the database for?

2020-05-16 09:16 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +    with filepath.open() as file:
Should I do that?

If we use `with` to open the file, all the file related code gets separately indented and there is no need to explicitly call the `.close()` function
It simplifies exception handling by encapsulating common preparation and cleanup tasks, thus ensuring that a clean-up is always used.

2020-05-16 09:17 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +    prefix = {'austria':'de', 'belgium':'nl', 'germany':'de', 'italy':'it', 'netherlands':'nl'}
Yes,
`de` refers to German
`nl` is Dutch
And `it` is Italian

2020-05-16 09:21 UTC, Hephaestus12 commented
> I think I've answered these questions in the email I sent you :) python 3.5 would be okay for now. 

Yes okay, I'm sorry I think I missed that email :')

2020-05-16 09:25 UTC, Hephaestus12 commented
> > Also, for the web app, should I set up a database and use something like SQLAlchemy(a python wrapper for SQL) or simply use pandas and csv files?
> 
> mmh what do you plan to use the database for? 

For displaying the data related to each day's estimated incidence, we need to send the API calls for every single keyword. Each API call takes about half a second so it doesn't make sense to recollect this everytime.
Therefore I was thinking of a database/CSV file storing the old data (which you have collected) as well as the new data everyday, so that you only need to send the api requests once.

2020-05-16 09:40 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +    with filepath.open() as file:
Ok, should I do it that way? .open()  is a function of the pathlib Path class.

2020-05-16 10:11 UTC, geektoni commented
> > > Also, for the web app, should I set up a database and use something like SQLAlchemy(a python wrapper for SQL) or simply use pandas and csv files?
> > 
> > 
> > mmh what do you plan to use the database for?
> 
> For displaying the data related to each day's estimated incidence, we need to send the API calls for every single keyword. Each API call takes about half a second so it doesn't make sense to recollect this everytime.
> Therefore I was thinking of a database/CSV file storing the old data (which you have collected) as well as the new data everyday, so that you only need to send the api requests once.

Okay, it seems reasonable to have a database for this kind of task (you could also use it to store predicted influenza incidence, so you don't have to compute it every time).

2020-05-19 07:45 UTC, Hephaestus12 commented
There are a few files that will be generated as you run the code(`src` package in the model directory) package in the `model` directory. (Combined data, pickled model, etc).
Should I add these to the `.gitignore`?
Or should I push these files to the repository as well?

2020-05-19 09:07 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/notebooks/eda.ipynb
> +{
what is this notebook for?

2020-05-19 09:07 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +from shogun import *
`import shogun as sg`

2020-05-19 09:08 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +from shogun import LinearRidgeRegression as LRR
it would be better if you used the new API here, so this import can be removed

2020-05-19 09:08 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        features_train = RealFeatures(util.load_features(file_path).T)
`sg.create_features` ....

2020-05-19 09:08 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
`g.create_machine`  ... check the meta examples on how it all works

2020-05-19 09:09 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +"""
Please don do things like this. Either put a docstring or not, but no empty ones pls

2020-05-19 09:16 UTC, geektoni commented
> There are a few files that will be generated as you run the code(`src` package in the model directory) package in the `model` directory. (Combined data, pickled model, etc).
> Should I add these to the `.gitignore`?
> Or should I push these files to the repository as well?

It depends if those files are required to run the final pipeline. If they are not useful (e.g., `__pycache__`) then you should not include them in the repository.

2020-05-19 09:40 UTC, lgoetz commented on influenza_project/web/app.py
> +    prefix = {'austria':'de', 'belgium':'nl', 'germany':'de', 'italy':'it', 'netherlands':'nl'}
may be worth re-writing/re-nameing such that that's immediately obvious

2020-05-19 09:40 UTC, lgoetz commented on influenza_project/web/app.py
> +    with filepath.open() as file:
yes

2020-05-19 09:45 UTC, lgoetz commented
> Also, what python version should I use?
> Is there any requirement with respect to that?
> I have used 3.7 here, but as far as I know, Shogun can only be used on version 3.5
> 
> So, I should switch to that right? Or is this okay?



> > Also, for the web app, should I set up a database and use something like SQLAlchemy(a python wrapper for SQL) or simply use pandas and csv files?
> 
> mmh what do you plan to use the database for?

we may ultimately want to do something like this, but for now I would concentrate on getting the pipeline up and running, i.e. use pandas if that's easier

2020-05-19 09:46 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/notebooks/eda.ipynb
> +{
**e**xploratory **d**ata **a**nalysis ... I suggest you rename to make that obvious

2020-05-19 09:56 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +    with filepath.open() as file:
Done.

2020-05-19 10:09 UTC, Hephaestus12 commented on influenza_project/web/app.py
> +    prefix = {'austria':'de', 'belgium':'nl', 'germany':'de', 'italy':'it', 'netherlands':'nl'}
Oh okay, should I make another dictionary storing the language names and codes? Unfortunately, the codes will need to remain de, nl and it since that is what wikipedia uses in its API.

There is something I can do though:
```
language = {'austria':'german',
	'belgium':'dutch',
	'germany':'german',
	'italy':'italian',
	'netherlands':'dutch'}

prefix = {'german':'de'
	'dutch':'nl'
	'italian':'it'}
```
However, then to access the prefix, I'll need to use `prefix[language[country]]`. I thought that might get a little cumbersome. Should I implement it that way?

2020-05-19 10:10 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/notebooks/eda.ipynb
> +{
Okay, I'll do that.

2020-05-19 10:11 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
Okay will do that.

2020-05-19 10:12 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +"""
That was left blank by mistake, I am supposed to fill it with basic data about the file. Sorry.

2020-05-19 10:26 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
Should I use `read_csv()` to read the files? Or is what I'm doing with pandas fine?
Asking because I remember reading somewhere that the file reading implementation in shogun is a little slow/buggy and so it is advised to use some external library for that.

2020-05-19 10:28 UTC, gf712 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
imo pandas is fine, in particular if you want to later on move from csv to sql

2020-05-19 11:08 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
I'm a little stuck, I am using `python 3.5` and have the `shogun 6.1.3` installed from conda-forge using conda.
However when I replace the old API with a new one, I get the following error:
```
features_train = sg.create_features(util.load_features(file_path).T)
AttributeError: module 'shogun' has no attribute 'create_features'
```
Is there something I am missing?

2020-05-19 11:18 UTC, gf712 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
I see, the suggestion is only compatible with the latest develop.

2020-05-19 11:26 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
So, it's not possible to use conda to install shogun? What should I do?

2020-05-19 11:48 UTC, gf712 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
You could compile shogun? Is there a reason why you are using the version from cinda?

2020-05-19 12:54 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
I will need to upload the model to the web tool, so on the virtual environment of the server, I guess the only way to install shogun is conda or pip right?
Will it be possible to upload the entire source code and compile it on the server?

2020-05-19 13:02 UTC, gf712 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
Yes. I assume you will be using docker for the environment? You can just build it in the docker image. Btw for serialisation you mention pickle, but I think using shoguns JSON serialiser is safer

2020-05-19 13:06 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
Oh okay fine.
I'll compile and install shogun.

2020-05-19 17:05 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
You will definitely need to compile the dev version, as you want to use your added model ...
Make sure to re-use the docker image and scripts we have, it compiles out of the box on there ...

2020-05-19 17:05 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +"""
no problem at all, I am just nitpicking a bit to keep things tidy :)

2020-05-26 14:09 UTC, geektoni requested changes
This initial PR is getting good to be merged! 

One thing which needs to be done before merging this would populate the README files with some basic instruction about how to run/install all of this (at least the data cleaning part).

2020-05-26 14:09 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/clean.py
> +    countries = ['austria', 'belgium', 'germany', 'italy', 'netherlands']
Could it be possible to fetch this information from like a configuration file rather than keeping everything hard-coded?

2020-05-26 14:09 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/combine.py
> +    countries = ['austria', 'belgium', 'germany', 'italy', 'netherlands']
Same here

2020-05-26 14:09 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/keywords/keywords_austria.txt
> +Epidemie
Just a quick question here, are these files really needed? Would it be possible to fetch them from the dataset submodule rather than copying them?

2020-05-26 17:06 UTC, Hephaestus12 commented
> This initial PR is getting good to be merged! 
> 
> One thing which needs to be done before merging this would populate the README files with some basic instruction about how to run/install all of this (at least the data cleaning part). 

Yes I'll do this.

2020-05-27 10:37 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/clean.py
> +    countries = ['austria', 'belgium', 'germany', 'italy', 'netherlands']
Yes, that sounds like a better idea.

2020-05-27 10:38 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/keywords/keywords_austria.txt
> +Epidemie
Yes, we can fetch it from there for now. But it will have to be uploaded to the web(only the web directory will be uploaded) So then later it may be a problem?

2020-05-27 10:54 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
I'm sorry, should I use this [docker image](https://hub.docker.com/r/shogun/shogun-dev) or compile manually as mentioned [here](https://www.shogun-toolbox.org/install#manual)?

2020-05-27 11:00 UTC, gf712 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        model = LRR(tau, features_train, labels_train)
I think you should create a Dockerfile that uses `FROM shogun-dev:latest` and then yes, clone shogun as per docs and compile with those commands

2020-06-04 14:06 UTC, geektoni requested changes
I added a few more comments. As you mentioned in the meeting, the web app is broken at the moment because it is not able to find some files. Would it be possible to place some dummy file to make it works?

Once the comments are addressed, I think this is ready to be merged. :)

2020-06-04 14:06 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        self.language = {'austria'    : 'german',
Also these should go into the config file (it will become easier to extend this to there countries).

2020-06-04 14:06 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
These are interesting! :) It would be better to document them a bit such to better understand what they should return.

2020-06-04 14:06 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        process.add_polynomial_features(country, df, 10)
Not sure if adding polynomial features could be worth it. @lgoetz any opinions?

2020-06-05 11:56 UTC, geektoni commented
Executing `flask run` still results in this error:
```
FileNotFoundError: [Errno 2] File b'/home/gdetoni/Github/applications/gsoc_application_projects/2020/influenza/web/influenza_estimator/data/austria.csv' does not exist: 
b'/home/gdetoni/Github/applications/gsoc_application_projects/2020/influenza/web/influenza_estimator/data/austria.csv'
```
This needs fixing before merging. You could already place the cleaned data files there, so to make it work again.

2020-06-05 13:11 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        process.add_polynomial_features(country, df, 10)
Like I said before, I would keep it simple, so no. But happy to be convinced otherwise if they give you an improvement

2020-06-05 13:38 UTC, lgoetz requested changes
Nice! we've already discussed (email/meeting/irc) some of the comments I've made -- please make sure you take notes of these, so we don't have to make the same comments again and again

2020-06-05 13:38 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        self.random_forest = {}
I'm confused, you've given up on the ridge regression now?

2020-06-05 13:38 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/process.py
> +    # add 3 polynomial features each for the most important features.
as we've discussed (email/meeting), you shouldn't really have to do a manual feature selection. By how much do your polynomial features improve the model?

2020-06-05 13:38 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/sample.py
> +import shogun as sg
why is this called sample.py?

2020-06-05 13:38 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/README.md
> +virtualenv is used to manage Python packages for different projects. Using virtualenv allows you to avoid installing Python packages globally which could break system tools or other projects. You can
If you copy-paste content from PyPA, you need to reference it!

2020-06-05 13:38 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
100%

2020-06-05 13:45 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/process.py
> +    # add 3 polynomial features each for the most important features.
Yes, I have to remove this. I'm sorry this isn't the final push for today, I'll have it removed, just that I was testing something out and so had to push once. It shall be rectified.

2020-06-05 13:46 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        self.language = {'austria'    : 'german',
Yes , I'll do this.

2020-06-05 13:47 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
Yes. I'll add some documentation related to the API.

2020-06-05 13:47 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        process.add_polynomial_features(country, df, 10)
Yes, I'll have that section removed.

2020-06-05 13:52 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        self.random_forest = {}
I had taken that decision on the basis of the consistently lower MSE I got. However, I am yet to find out how their performances compare when using the pearson correlation coefficient.

2020-06-05 13:53 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/sample.py
> +import shogun as sg
This was the code I had used to check if shogun was working fine. Its playing the role of a trivial example here. Should I delete it now?

2020-06-05 13:53 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/README.md
> +virtualenv is used to manage Python packages for different projects. Using virtualenv allows you to avoid installing Python packages globally which could break system tools or other projects. You can
Yes, I forgot to do that, I'll make that change.

2020-06-05 17:03 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        pickle.dump(self, open(str(config.model_path.absolute()), "wb"))
does this actually work? This class has shogun models as members ....

2020-06-05 17:04 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        labels_predict = self.random_forest[country].apply_regression(
just `apply`

2020-06-05 17:04 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        labels_predict = self.random_forest[country].apply_regression(
(should work and is compatible with new api, `apply_regression` is not

2020-06-05 17:06 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/process.py
> +    def apply_std_normal(self, df, numerical_features, means, std_deviations):
this could technically be done with shogun as well ... (though not necessary of course)

2020-06-05 17:07 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/sample.py
> +import shogun as sg
why not make a python test from it?

2020-06-05 17:08 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/sample.py
> +sg_storage = sg.DynamicObjectArray()
this doesnt need to be here (actually you can delete the whole file if it is not needed anymore)

2020-06-05 17:08 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        process.add_polynomial_features(country, df, 10)
polynomial features up to order 2-3 but not more
Also, this should be checked, what works best?

2020-06-05 17:09 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        print("X_train : " + str(X_train.shape))
I'd remove such print statements

2020-06-05 17:10 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    if path.exists() and path.is_file():
and otherwise? return None? Throw an error might be better  no?

2020-06-05 17:10 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/web/README.md
> +pip is the reference Python package manager. It’s used to install and update packages. You’ll need to make sure you have the latest version of pip installed.
no need to have this section, keep it to the stuff that cannot be found online

2020-06-05 17:11 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/web/README.md
> +venv (for Python 3) and virtualenv (for Python 2) allow you to manage separate package installations for different projects. They essentially allow you to create a “virtual” isolated Python installat
no need

2020-06-05 17:11 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/web/README.md
> +export FLASK_APP=influenza_estimator
imo this file should contain a one liner to install/run the tool, not an intro to what the different python tools do

2020-06-05 17:12 UTC, karlnapf commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        countries = ['austria', 'belgium', 'germany', 'italy', 'netherlands']
++

2020-06-05 17:12 UTC, karlnapf reviewed
Do the pickle files really need to be in the repo?

Nice work otherwise! :)

2020-06-05 21:04 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/process.py
> +    # add 3 polynomial features each for the most important features.
Cool, just checking

2020-06-05 21:04 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/README.md
> +virtualenv is used to manage Python packages for different projects. Using virtualenv allows you to avoid installing Python packages globally which could break system tools or other projects. You can
... and probably check they're/their license is OK with it

2020-06-05 21:04 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/README.md
> +export FLASK_APP=influenza_estimator
I kind of like the idea of having everything you need to know in one place. But since it's literally just a copy-paste, I agree, a link would probably do

2020-06-07 10:55 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
You are referring to comments? Or like a file explaining how to use the API?

2020-06-07 11:00 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        labels_predict = self.random_forest[country].apply_regression(
Okay, However, when I use apply(), I get an error that the regression lables are not compatible with multiclass or something on those lines...

2020-06-07 11:40 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
Added. check[ here.](https://github.com/Hephaestus12/applications/tree/master/gsoc_application_projects/2020/influenza/web#influenza-api-guide)

2020-06-07 11:42 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/README.md
> +virtualenv is used to manage Python packages for different projects. Using virtualenv allows you to avoid installing Python packages globally which could break system tools or other projects. You can
For now, I've removed it completely and replaced it with a link to Giovanni's blog. ;) I think the user be able to install Shogun correctly before running our web app is more important.

2020-06-07 11:43 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        print("X_train : " + str(X_train.shape))
Can I just make sure that my model completely works first, I'm currently a little stuck with the serialization issue. I'll surely remove it later. Is that okay?

2020-06-07 11:44 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    if path.exists() and path.is_file():
You mean like an exception? Or simply print an error message?

2020-06-07 11:45 UTC, Hephaestus12 commented
I have tried to address all changes, looking forward to getting this PR merged. I'm sorry if I have missed something. Please let me know.

2020-06-07 17:45 UTC, lgoetz requested changes
just added few more comments, but these are minor.

2020-06-07 17:45 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +        print("X_train : " + str(X_train.shape))
Sure, as long as you don't forget ;P

2020-06-07 17:45 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
it's a bit confusing: what is meant by "older" influenza incidence/estimate etc?

2020-06-07 17:47 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/api_v1.py
> +@bp.route('/all/current/', methods=['GET'])
Thanks for adding it, just make sure it's really useful ;)

2020-06-07 17:51 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/web/README.md
> +virtualenv is used to manage Python packages for different projects. Using virtualenv allows you to avoid installing Python packages globally which could break system tools or other projects. You can
sure, that's a good idea. You could add a link to the relevant page of the PyPA documentation for what you've now dropped.

2020-06-09 07:23 UTC, vigsterkr reviewed
some ideas

2020-06-09 07:23 UTC, vigsterkr commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        self.random_forest = {}
ok here's a radical crazy thought: why do we tie this thing to be a specific model? why isn't it just model, that follows a specific interface (say in case of shogun train/apply, or in sklearn-style fit/predict) and then this becomes totally interchangable for model type...

2020-06-09 07:23 UTC, vigsterkr commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        labels_predict = self.random_forest[country].apply_regression(
here's another crazy idea: why the model is actually here not an onnx model? so that this project could actually could use any type of model trained *anywhere* by *anything*. since here the model class is actually coupled with train, that kind of enforces you to have the model trained here by this class.... wouldn't it be better that if i know how to train a crazy model with the right pipeline outside of this thing just be able to plug it in here for prediction?

i guess i'm saying is that there should be a PredictMixin, that holds a general model that does model.apply/predict with the input features.... and in that case PredictMixin actually can simply be a wrapper around onnxruntime, so that totally decouples the whole SDK dependency of an ML library for deploying this for predicting things....

2020-06-09 08:41 UTC, Hephaestus12 commented
>ok here's a radical crazy thought: why do we tie this thing to be a specific model? why isn't it just model, that follows a specific interface (say in case of shogun train/apply, or in sklearn-style fit/predict), and then this becomes totally interchangeable for model type...

Yes, that's be great but afaik there are different kinds of data preprocessing to do before applying specific models? How will we deal with that?
We can do that with sklearn pipelines but coming to Shogun, if we use pipelines, we will be constrained to a limited set of preprocessing techniques which may not be enough at the moment right?

2020-06-09 17:55 UTC, lgoetz commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +        self.random_forest = {}
I like this idea, but imo for now we should focus on getting everything up and running with a simple regression first, then finish the Poisson regression (this PR is also still in progress) and *then* we can make the model interchangeable

2020-06-10 04:25 UTC, vigsterkr commented
> > ok here's a radical crazy thought: why do we tie this thing to be a specific model? why isn't it just model, that follows a specific interface (say in case of shogun train/apply, or in sklearn-style fit/predict), and then this becomes totally interchangeable for model type...
> 
> Yes, that's be great but afaik there are different kinds of data preprocessing to do before applying specific models? How will we deal with that?
> We can do that with sklearn pipelines but coming to Shogun, if we use pipelines, we will be constrained to a limited set of preprocessing techniques which may not be enough at the moment right?

the preprocessing could be done outside of the model per se.... meaning that the model is just literally the specific ML model and how you end up having `X,y` data set is another separate procedure... you fix what the model should expect as input. this allows you to interchange the model under the hood...

2020-06-10 04:29 UTC, vigsterkr commented
> > i guess i'm saying is that there should be a PredictMixin, that holds a general model that does model.apply/predict with the input features.... and in that case PredictMixin actually can simply be a wrapper around onnxruntime, so that totally decouples the whole SDK dependency of an ML library for deploying this for predicting things....
> 
> This seems like a really cool idea, I'll start reading about how to implement this. However, then this app will no longer be standalone. As in the idea of you pulling a docker image and running the web app out of the box may not work... if I understand you correctly.

this would simply allow anybody to use the app for predicting and that you externalize how you end up getting the model. of course you would still be able to do everything within a docker image, but if you have a different model with different backend that you would like to serve with the app, that would still be possible. one wouldn't need to refactor the app and change this initial entanglement of a model to a specific sdk to be able to do predictions...

2020-06-10 08:25 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        print(self.df[country].columns.values)
These `print` statements must be gone to merge this. They are useful if you need to manual debug what you are doing, but you should not add them to the committed files :)

2020-06-10 08:27 UTC, vigsterkr commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        print(self.df[country].columns.values)
what about instead of removing start using logging https://flask.palletsprojects.com/en/1.1.x/logging/

2020-06-10 08:30 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        print(self.df[country].columns.values)
> what about instead of removing start using logging https://flask.palletsprojects.com/en/1.1.x/logging/

That's even better!

2020-06-10 08:33 UTC, geektoni commented
I've noticed that the process which the application uses to download the current pageviews is kind of slow. I guess this happens because we are using just one thread to call Wikipedia's APIs. Could it be possible to parallelize it a bit more such to make the download faster?

2020-06-15 09:52 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +        print(self.df[country].columns.values)
I have implemented this.

2020-06-18 09:06 UTC, geektoni requested changes
I have done some nitpicking and I have left some more comments. Hopefully, this will be last review round before merging this PR :)

2020-06-18 09:06 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +
When the web application starts, we should disable shogun's custom signal handler. It could be possible to do it by calling
```python
sg.env().signal().enable_handler(False)
```
Ideally, it should be done somewhere within the web code.

2020-06-19 05:59 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/README.md
> +# Influenza Estimator Web Tool
Yes, I'll add that.

2020-06-19 06:00 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/process.py
> +            # # separate numerical features from categorical ones
Not really, now that everything else is running, I'll remove it.

2020-06-19 06:00 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/README.md
> +## GSOC 2020 Influenza Project
Okay fine.

2020-06-19 06:01 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/Dockerfile
> +ENV PYTHONPATH=/installed/shogun-install/lib/python3.5/site-packages/shogun.py
Oh yes, I had forgotten to push the updated Dockerfile.

2020-06-19 06:02 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +                    res = pageviewapi.per_article(project, line.strip(), start,
Hmm, yes, this makes sense. I'll check which exception is thrown when that happens and log it.

2020-06-19 06:03 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/model.py
> +
Oh okay, I'll add this.

2020-06-19 18:14 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/util.py
> +            logging.info('\tmaking API calls again.')
It'll happen inside a file called `information.log`

2020-06-20 14:41 UTC, geektoni requested changes

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/README.md
> +Seasonal influenza epidemics result in about three to five million cases of severe illness and about ​ 250,000 to 500,000 deaths worldwide each year. This is of utmost significance for public health
```suggestion
Seasonal influenza epidemics result in about three to five million cases of severe illness and about ​ 250,000 to 500,000 deaths worldwide each year. This is of utmost significance for public health agencies to reduce the effects of natural pandemics and epidemics such as H1N1 influenza. Results have demonstrated that protective steps can be taken to suppress epidemics where there is early warning during outbreak germination. Monitoring and forecasting the occurrence and spread of flu in the community is critical.
```

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/README.md
> +In the EU, there are several government institutions which track incidents of influenza-like disease (ILI)​ by gathering statistics from sentinel care activities that provide virological(the study of
```suggestion
In the EU, there are several government institutions which track incidents of influenza-like disease (ILI)​ by gathering statistics from sentinel care activities that provide virological statistics as well as clinical details, such as physicians reporting on the number of patients observed presenting influenza-like disease, obtaining and releasing information on a weekly basis.
```

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/README.md
> +This project is majorly based on the findings of David J. McIver and John S. Brownstein. In their research paper titled Wikipedia Usage Estimates Prevalence of Influenza-Like Illness in the United St
You should add a link to the original paper for reference (e.g., https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003581)

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/README.md
> +    Austria: FluNet surveillance tool
You should add link references for each of these services.

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/README.md
> +In an attempt to use Wikipedia data to estimate ILI activity, some researchers compiled a list of Wikipedia articles that were likely to be related to influenza, influenza-like activity, or to health
Missing link to zenodo?

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/sample.py
> +import shogun as sg
Do we still need this file here? Otherwise it could be wise to remove it.

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +from pathlib import Path
What is the purpose of this file? Is it testing all the methods you wrote so far?

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    if path.exists() and path.is_file():
I would just return `None` if the file is not found and check the result when we call this method. I guess this is applicable to all the methods in this file.

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/README.md
> +# Influenza Estimator Web Tool
If I try to pull the docker image I get the following error:
```
Using default tag: latest
Error response from daemon: manifest for tejsukhatme/influenza_estimator:latest not found: manifest unknown: manifest unknown
```
I guess you meant to write `docker pull tejsukhatme/influenza_estimator:random_forest` instead, right? :) It could be better to tag the docker image as `latest` so it will be downloaded automatically without the need to specify each time the tag.

2020-06-20 14:41 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/README.md
> +docker run tejsukhatme/influenza_estimator
```suggestion
docker run -it -p 5000:5000 tejsukhatme/influenza_estimator
```

2020-06-22 15:08 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +from pathlib import Path
No no, it is the code that split the data into training and testing datasets for judging which model is better.

2020-06-22 15:18 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/README.md
> +docker run tejsukhatme/influenza_estimator
I was thinking of adding different models in the future so this nomenclature would help.

2020-06-22 15:24 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/test.py
> +from pathlib import Path
Ah okay, I was confused by the name of the file :)

2020-06-22 15:24 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/README.md
> +docker run tejsukhatme/influenza_estimator
mmh then I would update at least the pull command, since the current one doesn't work.

2020-06-22 19:30 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    return None
Good! However, since these methods can return `None`, what does happen where these methods are called? Are you throwing an error if they return `None`? Are there any checks?

2020-06-23 12:11 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    return None
No, I haven't implemented any such checks. Also, for now this code isn't being used as we are doing everything(training and applying) in the web directory. Should I throw the errors and make checks?

I don't think we need to train the model separately and put the serialized version as training on the go takes negligible time, right?

2020-06-23 12:48 UTC, geektoni commented on gsoc_application_projects/2020/influenza/model/src/util.py
> +    return None
I would suggest you to update the model's code to do some checks when loading the features (e.g., if ``load_features`` returns `None` then print an error to the user and exit). 

In general, it would be better to provide already serialized models for many good reasons. However, since we had problems with that, let's skip it for now. We could do it later on.

2020-07-16 23:52 UTC, Hephaestus12 commented
Should I resolve the conversations? I have implemented most of the changes.

2020-07-17 09:39 UTC, karlnapf commented
I think it would be good to merge this huge thing soon, and then to work on smaller PRs
@Hephaestus12 I think it would be good if you could post a TODO list here (and in all bigger PRs in fact), and indicate what is done/missing

* [ ] example
* [x] bla

2020-08-05 10:02 UTC, Hephaestus12 commented
I made an entirely new install directory and installed from scratch, but I still get this error when trying to call GLM. Why might that be?

```
Class GLM with primitive type SGOBJECT does not exist.
```

2020-08-05 10:07 UTC, Hephaestus12 commented
And when I go to the python terminal and type `import shogun`
I am getting this:
```
ImportError: /home/tejsukhatme/anaconda3/envs/python3.5/lib/python3.5/_shogun.so: undefined symbol: _ZNK6shogun8SGObject12shallow_copyEv
```
This is the entire error message: https://pastebin.com/fSNDrFsq

2020-08-05 10:37 UTC, gf712 commented
> And when I go to the python terminal and type `import shogun`
> I am getting this:
> 
> ```
> ImportError: /home/tejsukhatme/anaconda3/envs/python3.5/lib/python3.5/_shogun.so: undefined symbol: _ZNK6shogun8SGObject12shallow_copyEv
> ```
> 
> This is the entire error message: https://pastebin.com/fSNDrFsq

Are you talking about the docker image?

2020-08-05 13:13 UTC, Hephaestus12 commented
> Are you talking about the docker image?

No, I was trying to get it to work on my machine environment first.

2020-08-05 18:30 UTC, gf712 commented
That’s because the newly compiled shogun library is not in the library path

2020-08-08 07:05 UTC, Hephaestus12 commented
When I try to train the model in python, it stores all weights as nan, I don't understand why. This is the serialized GLM:
```
GLM(num_subscriptions={function},
max_train_time=0,
labels=RegressionLabels(...)
 solver_type=ST_AUTO,
w=Vector<439>( -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan ),
bias=-nan,
features=DenseFeatures(...),
current_iteration=1000,
max_iterations=1000,
complete=false,
continue_features=DenseFeatures(...), 
seed=0,
set_random_seed={function},
distribution_type=POISSON,
eta=2,
lambda=0.1,
alpha=0.5,
tolerance=1e-06,
learning_rate=0.2)
```

2020-08-10 17:24 UTC, karlnapf commented
@Hephaestus12 I think if you have those issues, either drop by irc and ask, or send an email to the list. That is a quicker way to get an answer than here in this huge PR :)

2020-08-13 08:02 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/poisson/util.py
> +def load_features(path):
What is the difference between these methods and the ones in `src/utils.py`?

2020-08-13 09:01 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/poisson/util.py
> +def load_features(path):
utils.py are the utility functions for the web app, this is just for the model. However, I've refactored the code a little and removed this for now.

2020-08-13 09:10 UTC, geektoni commented on gsoc_application_projects/2020/influenza/web/influenza_estimator/poisson/util.py
> +def load_features(path):
okay!

2020-08-13 10:46 UTC, merged

2020-08-13 11:15 UTC, karlnapf commented
:partying_face: