Add Dashboard using Plotly Dash.
shogun-toolbox/applications pull request #4
Opened 2020-08-25 13:17 UTC by Hephaestus12

2020-08-26 07:39 UTC, geektoni requested changes
I've added some commits of general nitpicking :) I am just wondering why there are so many classes copied directly from the previous code for the web application. Is it possible to reuse them or do you plan to delete the old ones instead?

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    # print(df['austria'])
These comments should be deleted. You could also keep them by logging their output somewhere if you need them for debug purposes.

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +                # print("Row is: ")
Same here

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +@app.callback(Output("country_names", "value"), [Input("country_selector", "value")])
It would be nice to add a couple of lines that explain what do these methods do.

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/assets/resizing_script.js
> +window.dash_clientside.clientside = {
If you took this code from somewhere, you should cite the source. Not super important since there is no proper copyright on it (i think) but it is just to acknowledge the person which wrote it.

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/random_forest/model.py
> +class Model:
I reckon that you initially wrote a different piece of code to instantiate a model (`model/src/model.py`), why did you write another one here? Couldn't you use the previous one?

2020-08-26 07:39 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/util.py
> +class DataGateway:
Again here, why did you copy code around and you didn't use the one you wrote during the previous iteration? Did you need to add new functionalities or was it not performing the way we wanted?

2020-08-26 14:46 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/dash/util.py
> +class DataGateway:
Here, I've made the `web` and `dash` as standalone applications, when I make the docker container, I'll just be copying the dash folder to that and it'll work. That's why this file had to be transferred here. Also, the old and new web tools are basically two entirely different python flask web applications.
About the `model` directly, it is simply the notebooks and scripts which were used to process the data and develop the models.
Basically, the three directories are all independent.

2020-08-26 14:48 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/dash/util.py
> +class DataGateway:
> Here, I've made the `web` and `dash` as standalone applications, when I make the docker container, I'll just be copying the dash folder to that and it'll work. That's why this file had to be transferred here. Also, the old and new web tools are basically two entirely different python flask web applications.
> About the `model` directly, it is simply the notebooks and scripts which were used to process the data and develop the models.
> Basically, the three directories are all independent.

Is this okay? Or should I make any changes?

2020-08-26 22:18 UTC, Hephaestus12 commented
Commented code removed.
Now this saves calculated estimates as well :)

2020-08-26 23:29 UTC, Hephaestus12 commented
All that's left now is to upload it to dockerhub.

2020-08-27 10:47 UTC, Hephaestus12 commented
https://hub.docker.com/r/tejsukhatme/influenza_estimator <-------done :)

2020-08-27 19:20 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +# Controls What is diaplyed on the main map
```suggestion
# Controls What is displayed on the main map
```

2020-08-27 20:01 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/util.py
> +class DataGateway:
mmmh I am not sure if I understand how the things are structured now. Why do we have two separate applications and not just the one made with dash? or is it just one? Is there any reason why you kept also the old version of the interface? I am asking because, generally, you should avoid code duplication. Here, it seems that you have basically copy-pasted files around instead of reusing the ones you already wrote.

2020-08-27 20:03 UTC, geektoni commented
I was able to pull the new docker image and it looks very nice :) I also tried to play with the various options in the control panel but they do not seem to work yet. Secondly, I've seen that there are also other graphs which are still empty though. Could you elaborate a list of things which are missing and you still need to implement to have all the new interface up and running?

2020-08-27 22:38 UTC, Hephaestus12 commented
> I was able to pull the new docker image and it looks very nice :) I also tried to play with the various options in the control panel but they do not seem to work yet. Secondly, I've seen that there are also other graphs which are still empty though. Could you elaborate a list of things which are missing and you still need to implement to have all the new interface up and running?

I don't understand? Everything works when I run it, Can you send me a screenshot of your screen?

2020-08-28 07:13 UTC, geektoni commented
> > I was able to pull the new docker image and it looks very nice :) I also tried to play with the various options in the control panel but they do not seem to work yet. Secondly, I've seen that there are also other graphs which are still empty though. Could you elaborate a list of things which are missing and you still need to implement to have all the new interface up and running?
> 
> I don't understand? Everything works when I run it, Can you send me a screenshot of your screen?

I just checked again and the other graphs indeed work (not for all the possible combinations though). Would it be possible to set already some default values in the control panel such to have some data displayed form the beginning?

2020-08-28 11:27 UTC, Hephaestus12 commented
Yes, all possible combinations don't work, primarily because of the years.
For example, in the dataset, I only have access to the pageviews from one country for the year 2008. As a result if you choose just 2008 and some other country, it shows zero cases. I'll try to reduce the ambiguity in this.

2020-08-29 16:00 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/dash/assets/resizing_script.js
> +window.dash_clientside.clientside = {
Done.

2020-08-30 10:37 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +# Controls What is displyed on the main map
```suggestion
# Controls What is displayed on the main map
```

2020-08-30 10:37 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +# @server.route('/')
remove

2020-08-30 10:38 UTC, geektoni commented
Apart from some nitpicking now it seems to be right :) are these latest changes already on docker-hub?

2020-08-31 03:07 UTC, Hephaestus12 commented
> Apart from some nitpicking now it seems to be right :) are these latest changes already on docker-hub?

Thanks, and yes, it is published to docker-hub.

2020-08-31 13:10 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/Dockerfile
> +CMD ["python", "app.py", "-h", "0.0.0.0", "-p", "5000"]
What is the purpose of these flags (`-h` and `-p`)? I think they are not used by `app.py`.

2020-08-31 13:11 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    app.run_server(host='0.0.0.0', debug=False, port=8050)
Ahh I see, you hardcoded the various information here. Wouldn't it be possible to let the user specify the address/port so that he/she won't need to touch directly the source code?

2020-08-31 13:13 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    print(year_disable)
You forgot this `print` statement :)

2020-08-31 17:41 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    app.run_server(host='0.0.0.0', debug=False, port=8050)
I can remove it from here, but it'll have to be specified in some particular config file. I don't believe it's possible to set these at runtime.

2020-09-01 10:54 UTC, geektoni commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    app.run_server(host='0.0.0.0', debug=False, port=8050)
mmh I don't think it is mandatory. You can provide this information as command-line arguments. See https://docs.python.org/3/library/argparse.html#module-argparse

2020-09-01 11:48 UTC, Hephaestus12 commented on gsoc_application_projects/2020/influenza/dash/app.py
> +    app.run_server(host='0.0.0.0', debug=False, port=8050)
Ohh right, this is so cool. I'll implement this. :D

2025-10-30 14:02 UTC, closed without merging